<ul class="form-list checkout-agreements" id="payment_form_tlbarion" style="display:none;">
<li><a href="https://www.barion.com/hu/vasarlok/arak-vasarloknak/" target="_blank" rel="nofollow"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>tlsoft/barion/logo.png" alt="Barion" /></a><br />
A kényelmes és biztonságos online fizetést a Barion Payment Zrt. biztosítja.<br />
Magyar Nemzeti Bank engedély száma: H-EN-I-1064/2013<br />
Bankkártya adatai áruházunkhoz nem jutnak el.<br /></li>
</ul>